'use strict';

const OWNER = Object.freeze({
  APP: 'app',
  HERMES_BOUNDARY: 'hermes_boundary',
  HERMES_VOICE: 'hermes_voice',
  HERMES_PROVIDER: 'hermes_provider',
});

const EVENTS = Object.freeze({
  APP_READY: 'app_ready',
  AUTH_HANDOFF_OPENING: 'auth_handoff_opening',
  AUTH_HANDOFF_REQUESTED: 'auth_handoff_requested',
  AUTH_WINDOW_DOM_LOADED: 'auth_window_dom_loaded',
  AUTH_WINDOW_REQUESTED: 'auth_window_requested',
  AUTH_WINDOW_SHOWN_AND_FOCUSED: 'auth_window_shown_and_focused',
  CAT_SPAWN_SENT: 'cat_spawn_sent',
  CAT_SPAWN_RENDERED: 'cat_spawn_rendered',
  CLEANUP_DISMISS_COMPLETED: 'cleanup_dismiss_completed',
  CLEANUP_MODAL_CLOSED: 'cleanup_modal_closed',
  CONTEXT_CAPTURE_COMPLETED: 'context_capture_completed',
  CONTEXT_CAPTURE_FAILED: 'context_capture_failed',
  CONTEXT_CAPTURE_READY: 'context_capture_ready',
  CONTEXT_CAPTURE_STARTED: 'context_capture_started',
  CONTEXT_SNAPSHOT_CREATED: 'context_snapshot_created',
  GATEWAY_FIRST_EVENT: 'gateway_first_event',
  GATEWAY_HYDRATION_COMPLETED: 'gateway_hydration_completed',
  GATEWAY_HYDRATION_STARTED: 'gateway_hydration_started',
  GATEWAY_MESSAGE_POST_ACCEPTED: 'gateway_message_post_accepted',
  GATEWAY_MESSAGE_POST_FAILED: 'gateway_message_post_failed',
  GATEWAY_MESSAGE_POST_REQUESTED: 'gateway_message_post_requested',
  GATEWAY_PREWARM_COMPLETED: 'gateway_prewarm_completed',
  GATEWAY_PREWARM_STARTED: 'gateway_prewarm_started',
  GATEWAY_READY_CHECK_COMPLETED: 'gateway_ready_check_completed',
  GATEWAY_READY_CHECK_JOINED: 'gateway_ready_check_joined',
  GATEWAY_READY_CHECK_REUSED: 'gateway_ready_check_reused',
  GATEWAY_READY_CHECK_STARTED: 'gateway_ready_check_started',
  GATEWAY_REPLAY_EXPIRED: 'gateway_replay_expired',
  GATEWAY_RUNTIME_READY: 'gateway_runtime_ready',
  GATEWAY_TERMINALIZED: 'gateway_terminalized',
  MODAL_DOM_LOADED: 'modal_dom_loaded',
  MODAL_SHOW_REQUESTED: 'modal_show_requested',
  MODAL_SHOWN_AND_FOCUSED: 'modal_shown_and_focused',
  SESSION_WINDOW_OPEN_BLOCKED: 'session_window_open_blocked',
  SHORTCUT_INVOKED: 'shortcut_invoked',
  SHORTCUT_RECEIVED: 'shortcut_received',
  SHORTCUT_REGISTERED: 'shortcut_registered',
  SUBMIT_CONTEXT_READY: 'submit_context_ready',
  SUBMIT_REJECTED: 'submit_rejected',
  SUBMIT_REQUESTED: 'submit_requested',
  TERMINAL_STATE_RENDERED: 'terminal_state_rendered',
  VOICE_FINAL_TRANSCRIPT: 'voice_final_transcript',
  VOICE_PARTIAL_TRANSCRIPT: 'voice_partial_transcript',
  VOICE_SESSION_RECORDING_REQUESTED: 'voice_session_recording_requested',
  VOICE_SESSION_REJECTED: 'voice_session_rejected',
  VOICE_SESSION_TRANSCRIPT_READY: 'voice_session_transcript_ready',
  VOICE_STARTED: 'voice_started',
});

const STAGE_DEFS = Object.freeze([
  { id: 'app_ready_ms', label: 'App ready', owner: OWNER.APP },
  { id: 'shortcut_to_modal_visible_ms', label: 'Shortcut to launcher visible', owner: OWNER.APP },
  { id: 'context_capture_ms', label: 'Context capture', owner: OWNER.APP },
  { id: 'modal_visible_ms', label: 'Launcher visible', owner: OWNER.APP },
  { id: 'submit_to_pet_ms', label: 'Submit to pet visible', owner: OWNER.APP },
  { id: 'auth_window_visible_ms', label: 'Auth window visible', owner: OWNER.APP },
  { id: 'quit_reopen_hydration_ms', label: 'Quit/reopen hydration', owner: OWNER.HERMES_BOUNDARY },
  { id: 'gateway_ready_ms', label: 'Gateway readiness', owner: OWNER.HERMES_BOUNDARY },
  { id: 'gateway_post_ms', label: 'Gateway message post', owner: OWNER.HERMES_BOUNDARY },
  { id: 'submit_to_gateway_accepted_ms', label: 'Submit to gateway accepted', owner: OWNER.HERMES_BOUNDARY },
  { id: 'first_gateway_event_ms', label: 'Gateway accepted to first event', owner: OWNER.HERMES_BOUNDARY },
  { id: 'auth_handoff_ms', label: 'Auth handoff', owner: OWNER.HERMES_BOUNDARY },
  { id: 'voice_transcript_ms', label: 'Voice transcript ready', owner: OWNER.HERMES_VOICE },
  { id: 'conversation_terminal_ms', label: 'Conversation terminal', owner: OWNER.HERMES_PROVIDER },
]);

module.exports = {
  EVENTS,
  OWNER,
  STAGE_DEFS,
  SCHEMA_VERSION: 1,
};
